[versions]
jakarta-inject-api = "2.0.1"

[libraries]
# Micronaut
micronaut-http = { module = "io.micronaut:micronaut-http" }
micronaut-http-client = { module = "io.micronaut:micronaut-http-client" }
micronaut-http-server-netty = { module = "io.micronaut:micronaut-http-server-netty" }
micronaut-inject = { module = "io.micronaut:micronaut-inject" }
micronaut-reactor = { module = "io.micronaut.reactor:micronaut-reactor" }
micronaut-session = { module = "io.micronaut:micronaut-session" }
micronaut-validation = { module = "io.micronaut:micronaut-validation" }

jakarta-inject-api = { module = "jakarta.inject:jakarta.inject-api", version.ref = "jakarta-inject-api" }
