[versions]
micronaut = "4.0.0-M4"
micronaut-docs = "2.0.0"
micronaut-test = "4.0.0-M3"
groovy = "4.0.11"
spock = "2.3-groovy-4.0"

micronaut-reactor = "3.0.0-M4"
micronaut-serde = "2.0.0-M7"
micronaut-session = "4.0.0-M1"
micronaut-validation = "4.0.0-M7"

[libraries]
micronaut-session = { module = "io.micronaut.session:micronaut-session-bom", version.ref = "micronaut-session" }
micronaut-reactor = { module = "io.micronaut.reactor:micronaut-reactor-bom", version.ref = "micronaut-reactor" }
micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serde" }
micronaut-validation = { module = "io.micronaut.validation:micronaut-validation-bom", version.ref = "micronaut-validation" }
